# Generated by Django 5.2.4 on 2025-07-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default='', help_text='unique URL path for the post', unique=True),
        ),
    ]
