# Generated by Django 5.2.4 on 2025-07-26 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_alter_posts_author_alter_posts_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='emai_address',
            new_name='email_address',
        ),
    ]
